export default {
  API_BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001',
  API_ENDPOINTS: {
    AUTH_LOGIN: '/auth/login',
    AUTH_REGISTER: '/auth/register',
    AUTH_LOGOUT: '/auth/logout',
    AUTH_REFRESH: '/auth/refresh',
    AUTH_VERIFY: '/auth/verify',
  },
  PATHS: {
    ARTICLES: '/articles',
    BUDGET: '/budget',
    CATEGORIES: '/categories',
    CONTACT: '/contact',
    DASHBOARD: '/dashboard',
    FAQ: '/faq',
    FORGOT_PASSWORD: '/auth/forgot-password',
    PASSWORD_RESET: '/auth/password-reset',
    HOME: '/',
    INBOX: '/inbox',
    LOGIN: '/auth/login',
    NEW_ARRIVALS: '/new-arrivals',
    ORDERS: '/orders',
    PAYMENTS: '/payments',
    PRODUCTS: '/products',
    RETURNS: '/returns',
    SALE: '/sale',
    SETTINGS: '/settings',
    SHIPPING: '/shipping',
    USERS: '/users',
  },
} as const;
