/** Constants for the web app */
export default {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:3001',
  API_ENDPOINTS: {
    AUTH_LOGIN: '/auth/login',
    AUTH_REGISTER: '/auth/register',
    AUTH_LOGOUT: '/auth/logout',
    AUTH_REFRESH: '/auth/refresh',
    AUTH_VERIFY: '/auth/verify',
    AUTH_FORGOT_PASSWORD: '/auth/forgot-password',
    AUTH_RESET_PASSWORD: '/auth/reset-password',
    PRODUCTS_LIST: '/products',
    PRODUCTS_DETAIL: '/products/:id',
    ORDERS_LIST: '/orders',
    ORDERS_DETAIL: '/orders/:id',
    PAYMENTS_LIST: '/payments',
    PAYMENTS_DETAIL: '/payments/:id',
  },
  PATHS: {
    CART: '/cart',
    CATEGORIES: '/categories',
    CONTACT: '/contact',
    FAQ: '/faq',
    HOME: '/',
    LOGIN: '/login',
    NEW_ARRIVALS: '/new',
    ORDERS: '/orders',
    PRODUCTS: '/products',
    PROFILE: '/profile',
    RETURNS: '/returns',
    SALE: '/sale',
    SHIPPING: '/shipping',
    SIGNUP: '/signup',
  },
  CONTACT: {
    EMAIL: 'contact@ecommerce.com',
    PHONE: '+1 234 567 890',
  },
  SOCIAL: {
    FACEBOOK: 'https://facebook.com',
    INSTAGRAM: 'https://instagram.com',
    SNAPCHAT: 'https://snapchat.com',
    X: 'https://x.com',
  },
} as const;
